// Shared types for the anti-cheat town frontend

export type PlayerPhase = 'normal' | 'suspicious' | 'investigating' | 'confirmed' | 'punishing' | 'monitoring' | 'offline'

export type CheatType = 'fly' | 'speed' | 'kill_aura' | 'x_ray' | 'scaffold' | 'auto_clicker' | 'reach'

export type Confidence = 'low' | 'medium' | 'high'

export type Weather = 'clear' | 'rain' | 'thunder' | 'snow'

export type TimePeriod = 'dawn' | 'morning' | 'noon' | 'afternoon' | 'dusk' | 'night'

export interface Vec3 {
  x: number
  y: number
  z: number
}

export interface BuildingInfo {
  id: string
  name: string
  position: Vec3
  size: Vec3
  color: number
}

export interface MonitorStation {
  id: string
  position: Vec3
  occupied: boolean
  occupantId: string | null
  screenState: Record<string, unknown> | null
}

export interface NPCRole {
  id: string
  label: string
  color: number
}

export const PHASE_COLORS: Record<PlayerPhase, number> = {
  normal: 0x4a90d9,
  suspicious: 0xf1c40f,
  investigating: 0xe67e22,
  confirmed: 0xe74c3c,
  punishing: 0xff0000,
  monitoring: 0x2ecc71,
  offline: 0x7f8c8d,
}

export const PHASE_CSS_COLORS: Record<PlayerPhase, string> = {
  normal: '#4a90d9',
  suspicious: '#f1c40f',
  investigating: '#e67e22',
  confirmed: '#e74c3c',
  punishing: '#ff0000',
  monitoring: '#2ecc71',
  offline: '#7f8c8d',
}

export const PHASE_LABELS: Record<PlayerPhase, string> = {
  normal: '正常',
  suspicious: '可疑',
  investigating: '调查中',
  confirmed: '已确认',
  punishing: '处罚中',
  monitoring: '监控中',
  offline: '离线',
}

export const CONFIDENCE_LABELS: Record<Confidence, string> = {
  low: '低',
  medium: '中',
  high: '高',
}

export const CHEAT_TYPE_LABELS: Record<CheatType, string> = {
  fly: '飞行作弊',
  speed: '加速作弊',
  kill_aura: '杀戮光环',
  x_ray: '透视',
  scaffold: '自动搭桥',
  auto_clicker: '自动点击',
  reach: '攻击距离',
}

export const CHEAT_TYPE_COLORS: Record<CheatType, string> = {
  fly: '#9b59b6',
  speed: '#3498db',
  kill_aura: '#e74c3c',
  x_ray: '#f39c12',
  scaffold: '#1abc9c',
  auto_clicker: '#e67e22',
  reach: '#2ecc71',
}

export const CONFIDENCE_ORDER: Confidence[] = ['low', 'medium', 'high']

export interface AlertEntry {
  id: string
  playerId: string
  playerName: string
  cheatType: CheatType
  confidence: Confidence
  message: string
  timestamp: number
}

export interface Evidence {
  metric: string
  value: number
  threshold: number
  duration: number
}

export interface PhaseTransition {
  from: PlayerPhase
  to: PlayerPhase
  timestamp: number
}

export interface BanStatus {
  isBanned: boolean
  reason?: string
  duration?: string
  bannedAt?: number
  expiresAt?: number | null
  source?: string
}

export interface PlayerInfo {
  playerId: string
  name: string
  ip: string
  gameMode: string
  phase: PlayerPhase
  position: Vec3
  speed: number
  cps: number
  hitRate: number
  cheatRecordCount: number
  stationId?: string
  evidence: Evidence[]
  phaseHistory: PhaseTransition[]
  isTracked: boolean
  // VP 积分
  totalVP: number
  vpByType: Record<CheatType, number>
  penaltyCount: number
  // 封禁状态
  banStatus: BanStatus
}

export interface RecordsArchiveFilter {
  cheatType?: CheatType
  confidence?: Confidence
  dateFrom?: number
  dateTo?: number
  sortBy?: string
  sortDir?: 'asc' | 'desc'
  page?: number
  pageSize?: number
}

export interface CheatRecordEntry {
  id: string
  cheatType: CheatType
  confidence: Confidence
  timestamp: number
  action: string
  playerName?: string
  evidence?: Array<{ metric: string; value: number; threshold: number; duration: number }>
  vp?: number
}

export interface ServerStats {
  onlinePlayers: number
  totalPlayers: number
  activeAlerts: number
  alertsByType: Record<CheatType, number>
  totalBans: number
  whitelistCount: number
  totalPenalties: number
  autoPenalties: number
}

export type PenaltyLevel = 'L0' | 'L1' | 'L2' | 'L3' | 'L4' | 'L5'

export interface PenaltyLogEntry {
  penaltyId: string
  playerId: string
  playerName: string
  level: PenaltyLevel
  action: string
  cheatType: CheatType
  confidence: Confidence
  vp: number
  reason: string
  autoGenerated: boolean
  timestamp: number
}

export type InvestigationCaseStatus = 'open' | 'monitoring' | 'confirmed' | 'dismissed'
export type InvestigationRiskLevel = 'medium' | 'high' | 'critical'
export type InvestigationDecision = 'confirm' | 'dismiss' | 'monitor'

export interface InvestigationCaseSummary {
  id: string
  playerId: string
  npcId?: string
  playerName: string
  status: InvestigationCaseStatus
  riskLevel: InvestigationRiskLevel
  riskScore: number
  confidenceScore: number
  suspectedCheats: CheatType[]
  signalCount: number
  signals?: unknown[]
  openedAt?: number
  updatedAt: number
}

export interface DetectorQualityMetric {
  reviewedCases: number
  confirmedCases: number
  dismissedCases: number
  confirmationRate: number | null
}

export interface CaseQualityMetrics {
  reviewedCases: number
  confirmedCases: number
  dismissedCases: number
  confirmationRate: number | null
  dismissalRate: number | null
  averageHandlingTimeMs: number | null
  byDetector: Partial<Record<CheatType, DetectorQualityMetric>>
}

export interface OfflineSummary {
  from: number
  to: number
  durationMs: number
  onlinePeak: number
  casesOpened: number
  automaticMeasures: number
  minTps: number | null
  hasImportantActivity: boolean
  pendingCases: number
  quality: CaseQualityMetrics | null
}

export interface SemanticEvidenceContext {
  timestamp: number
  tps: number
  ping: number | null
  statusEffects: string[]
  exemptions: string[]
}

export type SemanticEvidenceEvent = SemanticEvidenceContext & ({
  type: 'movement'
  x: number; y: number; z: number
  vx: number; vy: number; vz: number
  onGround: boolean
} | {
  type: 'combat'
  victimId: string; distance: number; angle: number; cps: number; hasLos: boolean
} | {
  type: 'block'
  action: 'break' | 'place'; blockType: string; speed: number
  x?: number; y?: number; z?: number; exposedFaces?: number
  nearbyOres?: Array<{ type: string; dx: number; dy: number; dz: number; exposed: boolean }>
  yaw?: number; pitch?: number; placedFace?: string; placementIntervalMs?: number
} | {
  type: 'action'
  action: string; state: boolean
} | {
  type: 'detection'
  cheatType: CheatType; confidence: Confidence
  evidence: Evidence[]
})

export interface CaseEvidenceSnapshot {
  version: 1
  caseId: string
  playerId: string
  capturedAt: number
  windowStart: number
  windowEnd: number
  complete: boolean
  events: SemanticEvidenceEvent[]
  byteSize: number
  xrayAnalysis?: {
    sampleCount: number; valuableHits: number; valuableHitEfficiency: number
    shortestPathDeviation: number | null; crossSampleAnomaly: number
    turnCount: number; hiddenOreCount: number; hiddenDirectionMatches: number
    trajectory: Array<{ x: number; y: number; z: number; timestamp: number; valuable: boolean }>
    oreContext: Array<{ type: string; x: number; y: number; z: number; exposed: boolean }>
    comparison: { normal: string; suspicious: string }
  } | null
  physicsAnalysis?: {
    exceededFrames: number; exemptedFrames: number
    frames: Array<{ timestamp: number; actualHorizontalSpeed: number; legalHorizontalSpeed: number; actualVerticalSpeed: number; legalVerticalMin: number; legalVerticalMax: number; exemptions: string[] }>
  } | null
  scaffoldAnalysis?: {
    sampleCount: number; rapidPlacements: number; averageIntervalMs: number | null
    downwardLookRatio: number; unusualFaceRatio: number
    path: Array<{ x: number; y: number; z: number; timestamp: number; yaw: number; pitch: number; placedFace: string }>
  } | null
}

export const PENALTY_LEVEL_LABELS: Record<PenaltyLevel, string> = {
  L0: '警告',
  L1: '踢出',
  L2: '封禁(1小时)',
  L3: '封禁(24小时)',
  L4: '封禁(7天)',
  L5: '永久封禁',
}

export const PENALTY_LEVEL_COLORS: Record<PenaltyLevel, string> = {
  L0: '#f1c40f',
  L1: '#e67e22',
  L2: '#e74c3c',
  L3: '#c0392b',
  L4: '#8e44ad',
  L5: '#2c3e50',
}
