// @desc PenaltyEngine — 自动处罚决策引擎
//
// 接收检测结果，通过 VPManager 累加积分，判定处罚等级，
// 生成 SpigotAction，并记录处罚日志。

import type { CheatType, Confidence, SpigotAction, PlayerPhase } from '../contracts/index.js'
import { VPManager, PENALTY_THRESHOLDS, type PenaltyLevel, type PenaltyRecord } from './vp-manager.js'
import { randomUUID } from 'node:crypto'

export interface PenaltyResult {
  /** 是否触发了处罚 */
  triggered: boolean
  /** 处罚等级（null 表示未达阈值） */
  level: PenaltyLevel | null
  /** 生成的 SpigotAction（null 表示仅警告或未触发） */
  action: SpigotAction | null
  /** 附加动作（如 kick 时同时 ban） */
  supplementaryActions: SpigotAction[]
  /** 处罚记录 */
  record: PenaltyRecord | null
  /** 处罚后建议的 Phase */
  targetPhase: PlayerPhase | null
  /** 当前 VP 总分 */
  totalVP: number
}

export class PenaltyEngine {
  private vpManager: VPManager
  private enabled: boolean
  private actionRetryMax: number
  private actionRetryIntervalMs: number
  /** 待确认处罚的 VP 阈值记录：playerId → thresholdVP */
  private pendingThresholds = new Map<string, number>()

  constructor(vpManager: VPManager, opts?: {
    enabled?: boolean
    actionRetryMax?: number
    actionRetryIntervalMs?: number
  }) {
    this.vpManager = vpManager
    this.enabled = opts?.enabled ?? true
    this.actionRetryMax = opts?.actionRetryMax ?? 2
    this.actionRetryIntervalMs = opts?.actionRetryIntervalMs ?? 30_000
  }

  /** 核心评估方法：检测 → VP 累加 → 处罚判定 */
  evaluate(
    playerId: string,
    playerName: string,
    cheatType: CheatType,
    confidence: Confidence,
    isWhitelisted: boolean = false,
    ipWeight: number = 1.0,
  ): PenaltyResult {
    // 累加 VP
    const totalVP = this.vpManager.addVP(playerId, playerName, cheatType, confidence, isWhitelisted, ipWeight)

    // 未启用自动处罚时，仅记录 VP
    if (!this.enabled) {
      return { triggered: false, level: null, action: null, supplementaryActions: [], record: null, targetPhase: null, totalVP }
    }

    // 判定处罚等级
    const threshold = this.vpManager.resolvePenaltyLevel(playerId)
    if (!threshold) {
      // 未达阈值，确定 Phase
      const targetPhase = this.resolvePhaseFromVP(totalVP)
      return { triggered: false, level: null, action: null, supplementaryActions: [], record: null, targetPhase, totalVP }
    }

    // 检查是否已经在此等级处罚过（避免重复处罚）
    const recentPenalties = this.vpManager.getPenaltyHistory(playerId, 5)
    const lastPenalty = recentPenalties[recentPenalties.length - 1]
    if (lastPenalty && lastPenalty.level === threshold.level && Date.now() - lastPenalty.executedAt < 60_000) {
      // 1 分钟内同等级不重复处罚
      return { triggered: false, level: threshold.level, action: null, supplementaryActions: [], record: null, targetPhase: 'confirmed', totalVP }
    }

    // 生成处罚
    const penaltyId = `penalty-${playerId}-${Date.now()}`
    let action: SpigotAction | null = null
    let targetPhase: PlayerPhase | null = null
    const supplementaryActions: SpigotAction[] = []

    switch (threshold.action) {
      case 'warn': {
        // L0 警告：发送警告消息到 Spigot
        action = {
          type: 'warning',
          actionId: `act-${randomUUID().slice(0, 8)}`,
          playerId,
          reason: `[AntiCheat] 警告：检测到 ${cheatType} 作弊行为 (置信度: ${confidence})，请停止违规行为`,
        }
        targetPhase = 'suspicious'
        break
      }
      case 'kick': {
        // L1 踢出 + 临时封禁（防止立即重连）
        action = {
          type: 'kick',
          actionId: `act-${randomUUID().slice(0, 8)}`,
          playerId,
          reason: `[AntiCheat] 因 ${cheatType} 作弊行为被踢出 (VP: ${totalVP.toFixed(1)})`,
        }
        // 同时执行临时封禁（5分钟），防止玩家立即重连继续作弊
        supplementaryActions.push({
          type: 'ban',
          actionId: `act-${randomUUID().slice(0, 8)}`,
          playerId,
          reason: `[AntiCheat] 因 ${cheatType} 作弊行为临时封禁 (VP: ${totalVP.toFixed(1)})`,
          duration: '5m',
        })
        targetPhase = 'punishing'
        break
      }
      case 'ban': {
        // L2-L5 封禁
        let duration = threshold.duration
        duration = this.vpManager.applyRepeatOffender(playerId, duration)

        action = {
          type: 'ban',
          actionId: `act-${randomUUID().slice(0, 8)}`,
          playerId,
          reason: `[AntiCheat] 因 ${cheatType} 作弊行为被封禁 (等级: ${threshold.level}, VP: ${totalVP.toFixed(1)})`,
          duration,
        }
        targetPhase = 'punishing'
        break
      }
    }

    // 记录处罚
    const record: PenaltyRecord = {
      penaltyId,
      playerId,
      playerName,
      level: threshold.level,
      action: threshold.action,
      vpAtTime: totalVP,
      cheatType,
      confidence,
      duration: threshold.duration,
      reason: action?.reason ?? '',
      autoGenerated: true,
      executedAt: Date.now(),
      result: 'pending',
    }

    this.vpManager.addPenaltyRecord(record)

    // 处罚后 VP 不立即重置，等待 Spigot 确认执行成功后再重置
    // 记录阈值供 onPenaltyConfirmed 使用
    this.pendingThresholds.set(playerId, threshold.vp)

    return { triggered: true, level: threshold.level, action, supplementaryActions, record, targetPhase, totalVP }
  }

  /** 处理动作执行结果 */
  handleActionResult(actionId: string, success: boolean): void {
    // 由 ActionDispatcher 处理重试逻辑
    // PenaltyEngine 只记录日志
    if (!success) {
      console.warn(`[PenaltyEngine] Action ${actionId} failed, ActionDispatcher will retry`)
    }
  }

  /** 处罚动作确认执行成功后，重置 VP */
  onPenaltyConfirmed(playerId: string): void {
    const thresholdVP = this.pendingThresholds.get(playerId)
    if (thresholdVP !== undefined) {
      this.vpManager.resetVPAfterPenalty(playerId, thresholdVP)
      this.pendingThresholds.delete(playerId)
      console.log(`[PenaltyEngine] VP reset for ${playerId} after confirmed penalty (threshold: ${thresholdVP})`)
    }
  }

  /** 根据 VP 总分判定 Phase（未达处罚阈值时） */
  private resolvePhaseFromVP(totalVP: number): PlayerPhase | null {
    // investigating 阈值设为 L0-L1 之间的中点（约 10 VP），确保中等可疑度玩家可见
    if (totalVP >= (PENALTY_THRESHOLDS[0].vp + PENALTY_THRESHOLDS[1].vp) / 2) return 'investigating'
    if (totalVP >= PENALTY_THRESHOLDS[0].vp) return 'suspicious'    // VP >= L0 阈值
    return null // normal
  }

  /** 管理员手动处罚 */
  adminPenalty(
    playerId: string,
    playerName: string,
    actionType: 'kick' | 'ban' | 'freeze' | 'unban',
    reason: string,
    duration?: string,
    adminId?: string,
    cheatType?: CheatType,
  ): PenaltyRecord {
    const penaltyId = `admin-${playerId}-${Date.now()}`
    const totalVP = this.vpManager.getTotalVP(playerId)

    const record: PenaltyRecord = {
      penaltyId,
      playerId,
      playerName,
      level: 'L5', // 管理员操作默认最高等级
      action: actionType === 'freeze' ? 'kick' : actionType as 'kick' | 'ban' | 'warn',
      vpAtTime: totalVP,
      cheatType: cheatType ?? 'fly',
      confidence: 'high',
      duration: duration ?? 'permanent',
      reason: reason || '管理员操作',
      autoGenerated: false,
      adminId,
      executedAt: Date.now(),
      result: 'pending',
    }

    this.vpManager.addPenaltyRecord(record)

    // 管理员封禁后也重置 VP
    if (actionType === 'ban') {
      this.vpManager.resetVPAfterPenalty(playerId, PENALTY_THRESHOLDS[PENALTY_THRESHOLDS.length - 1].vp)
    }

    return record
  }

  /** 管理员解除处罚 */
  adminDismiss(playerId: string): void {
    this.vpManager.clearVP(playerId)
  }

  /** 获取 VPManager 引用 */
  getVPManager(): VPManager {
    return this.vpManager
  }

  /** 设置启用/禁用 */
  setEnabled(enabled: boolean): void {
    this.enabled = enabled
  }

  /** 是否启用 */
  isEnabled(): boolean {
    return this.enabled
  }
}
