// @desc VPManager — Violation Points 积分管理器
//
// 管理玩家违规积分 (VP) 的累加、衰减、查询和持久化。
// VP 是处罚决策的核心量化指标，替代仅靠置信度的粗粒度判定。

import type { CheatType, Confidence } from '../contracts/index.js'

// ── VP 权重配置 ──

export const VP_WEIGHTS: Record<Confidence, number> = {
  low: 1,
  medium: 3,
  high: 8,
}

export const VP_TYPE_MULTIPLIERS: Record<CheatType, number> = {
  kill_aura: 1.5,
  fly: 1.2,
  speed: 1.2,
  reach: 1.3,
  x_ray: 1.0,
  scaffold: 1.0,
  auto_clicker: 0.8,
}

// ── 处罚等级 ──

export type PenaltyLevel = 'L0' | 'L1' | 'L2' | 'L3' | 'L4' | 'L5'

export interface PenaltyThreshold {
  level: PenaltyLevel
  vp: number
  action: 'warn' | 'kick' | 'ban'
  duration: string // ban 持续时间
  label: string
}

export const PENALTY_THRESHOLDS: PenaltyThreshold[] = [
  { level: 'L0', vp: 5,   action: 'warn',  duration: '',          label: '警告' },
  { level: 'L1', vp: 15,  action: 'kick',  duration: '',          label: '踢出' },
  { level: 'L2', vp: 30,  action: 'ban',   duration: '1h',        label: '临时封禁(1小时)' },
  { level: 'L3', vp: 60,  action: 'ban',   duration: '24h',       label: '临时封禁(24小时)' },
  { level: 'L4', vp: 100, action: 'ban',   duration: '7d',        label: '临时封禁(7天)' },
  { level: 'L5', vp: 150, action: 'ban',   duration: 'permanent', label: '永久封禁' },
]

// ── 衰减配置 ──

const DECAY_INTERVAL_MS = 10 * 60 * 1000 // 10 分钟
const DECAY_AMOUNT = 1
const SNAPSHOT_INTERVAL_MS = 5 * 60 * 1000 // 5 分钟

// ── 数据结构 ──

export interface VPEntry {
  playerId: string
  playerName: string
  totalVP: number
  vpByType: Record<CheatType, number>
  penaltyCount: number
  lastPenaltyAt: number
  lastDetectionAt: number
  lastCheatType: CheatType // 最近一次检测到的作弊类型
  joinTime: number // 用于新玩家宽限期
}

export interface PenaltyRecord {
  penaltyId: string
  playerId: string
  playerName: string
  level: PenaltyLevel
  action: 'warn' | 'kick' | 'ban'
  vpAtTime: number
  cheatType: CheatType
  confidence: Confidence
  duration: string
  reason: string
  autoGenerated: boolean
  adminId?: string
  executedAt: number
  result: 'pending' | 'success' | 'failed' | 'reverted'
}

export class VPManager {
  private entries = new Map<string, VPEntry>()
  private penaltyHistory: PenaltyRecord[] = []
  private decayTimer: ReturnType<typeof setInterval> | null = null
  private snapshotTimer: ReturnType<typeof setInterval> | null = null
  private dataDir: string
  private whitelistMultiplier: number
  private newPlayerGraceMinutes: number
  private newPlayerVPMultiplier: number
  private repeatOffenderWindowDays: number
  private repeatDurationMultiplier: number
  private autoUpgradeOnNth: number

  constructor(dataDir: string, opts?: {
    whitelistMultiplier?: number
    newPlayerGraceMinutes?: number
    newPlayerVPMultiplier?: number
    repeatOffenderWindowDays?: number
    repeatDurationMultiplier?: number
    autoUpgradeOnNth?: number
  }) {
    this.dataDir = dataDir
    this.whitelistMultiplier = opts?.whitelistMultiplier ?? 2.0
    this.newPlayerGraceMinutes = opts?.newPlayerGraceMinutes ?? 5
    this.newPlayerVPMultiplier = opts?.newPlayerVPMultiplier ?? 0.5
    this.repeatOffenderWindowDays = opts?.repeatOffenderWindowDays ?? 30
    this.repeatDurationMultiplier = opts?.repeatDurationMultiplier ?? 1.5
    this.autoUpgradeOnNth = opts?.autoUpgradeOnNth ?? 3

    this.loadSnapshot()
    this.startDecayTimer()
    this.startSnapshotTimer()
  }

  // ── VP 操作 ──

  /** 累加 VP，返回累加后的总 VP */
  addVP(
    playerId: string,
    playerName: string,
    cheatType: CheatType,
    confidence: Confidence,
    isWhitelisted: boolean = false,
    ipWeight: number = 1.0,
  ): number {
    let entry = this.entries.get(playerId)
    if (!entry) {
      entry = {
        playerId,
        playerName,
        totalVP: 0,
        vpByType: { fly: 0, speed: 0, kill_aura: 0, x_ray: 0, scaffold: 0, auto_clicker: 0, reach: 0 },
        penaltyCount: 0,
        lastPenaltyAt: 0,
        lastDetectionAt: Date.now(),
        lastCheatType: cheatType,
        joinTime: Date.now(),
      }
      this.entries.set(playerId, entry)
    }

    // 计算基础 VP
    let baseVP = VP_WEIGHTS[confidence]
    let multiplier = VP_TYPE_MULTIPLIERS[cheatType]

    // 白名单玩家 VP 阈值 ×2（通过降低 VP 增量实现）
    if (isWhitelisted) {
      multiplier /= this.whitelistMultiplier
    }

    // 新玩家宽限期
    const graceMs = this.newPlayerGraceMinutes * 60 * 1000
    if (Date.now() - entry.joinTime < graceMs) {
      multiplier *= this.newPlayerVPMultiplier
    }

    // IP 关联权重（多账号共享 IP 时 VP 增量按比例累加）
    multiplier *= ipWeight

    const vpGain = Math.round(baseVP * multiplier * 100) / 100
    entry.totalVP += vpGain
    entry.vpByType[cheatType] += vpGain
    entry.lastDetectionAt = Date.now()
    entry.lastCheatType = cheatType

    return entry.totalVP
  }

  /** 获取玩家 VP 条目 */
  getEntry(playerId: string): VPEntry | undefined {
    return this.entries.get(playerId)
  }

  /** 获取玩家总 VP */
  getTotalVP(playerId: string): number {
    return this.entries.get(playerId)?.totalVP ?? 0
  }

  /** 重置玩家 VP（处罚后设为阈值的 60%） */
  resetVPAfterPenalty(playerId: string, thresholdVP: number): void {
    const entry = this.entries.get(playerId)
    if (!entry) return
    entry.totalVP = Math.round(thresholdVP * 0.6 * 100) / 100
    entry.penaltyCount++
    entry.lastPenaltyAt = Date.now()
  }

  /** 完全清除玩家 VP（管理员 dismiss） */
  clearVP(playerId: string): void {
    const entry = this.entries.get(playerId)
    if (!entry) return
    entry.totalVP = 0
    for (const key of Object.keys(entry.vpByType) as CheatType[]) {
      entry.vpByType[key] = 0
    }
  }

  /** 注册玩家加入时间 */
  registerPlayer(playerId: string, playerName: string): void {
    let entry = this.entries.get(playerId)
    if (!entry) {
      entry = {
        playerId,
        playerName,
        totalVP: 0,
        vpByType: { fly: 0, speed: 0, kill_aura: 0, x_ray: 0, scaffold: 0, auto_clicker: 0, reach: 0 },
        penaltyCount: 0,
        lastPenaltyAt: 0,
        lastDetectionAt: 0,
        lastCheatType: 'fly',
        joinTime: Date.now(),
      }
      this.entries.set(playerId, entry)
    } else {
      entry.playerName = playerName
      entry.joinTime = Date.now()
    }
  }

  /** 移除玩家（离线时保留 VP 数据，不删除） */
  removePlayer(playerId: string): void {
    // 保留 VP 数据，不删除 — VP 持久化到磁盘
  }

  // ── 处罚等级判定 ──

  /** 根据当前 VP 判定处罚等级，返回 null 表示未达阈值 */
  resolvePenaltyLevel(playerId: string): PenaltyThreshold | null {
    const entry = this.entries.get(playerId)
    if (!entry) return null

    // 反向遍历找最高匹配阈值（不依赖数组顺序）
    for (let i = PENALTY_THRESHOLDS.length - 1; i >= 0; i--) {
      if (entry.totalVP >= PENALTY_THRESHOLDS[i].vp) {
        return PENALTY_THRESHOLDS[i]
      }
    }
    return null
  }

  /** 检查累犯加重：返回调整后的 duration */
  applyRepeatOffender(playerId: string, duration: string): string {
    const entry = this.entries.get(playerId)
    if (!entry || entry.penaltyCount === 0) return duration

    if (duration === 'permanent') return duration

    const windowMs = this.repeatOffenderWindowDays * 24 * 60 * 60 * 1000
    const recentPenalties = entry.penaltyCount // 简化：使用总处罚次数

    // 第 N 次处罚自动升级
    if (recentPenalties >= this.autoUpgradeOnNth) {
      return this.upgradeDuration(duration)
    }

    // 重复违规：时长 ×1.5
    if (entry.lastPenaltyAt > 0 && Date.now() - entry.lastPenaltyAt < windowMs) {
      return this.multiplyDuration(duration, this.repeatDurationMultiplier)
    }

    return duration
  }

  /** 记录处罚 */
  addPenaltyRecord(record: PenaltyRecord): void {
    this.penaltyHistory.push(record)
    if (this.penaltyHistory.length > 10000) {
      this.penaltyHistory = this.penaltyHistory.slice(-10000)
    }
  }

  /** 获取处罚历史 */
  getPenaltyHistory(playerId?: string, limit: number = 50): PenaltyRecord[] {
    let records = this.penaltyHistory
    if (playerId) {
      records = records.filter(r => r.playerId === playerId)
    }
    return records.slice(-limit)
  }

  /** 获取所有 VP 条目 */
  getAllEntries(): VPEntry[] {
    return Array.from(this.entries.values())
  }

  // ── 衰减 ──

  private startDecayTimer(): void {
    this.decayTimer = setInterval(() => {
      this.runDecay()
    }, DECAY_INTERVAL_MS)
  }

  private runDecay(): void {
    const now = Date.now()
    for (const entry of this.entries.values()) {
      // 仅对超过 10 分钟未检测的玩家衰减
      if (now - entry.lastDetectionAt >= DECAY_INTERVAL_MS && entry.totalVP > 0) {
        entry.totalVP = Math.max(0, entry.totalVP - DECAY_AMOUNT)
        // 同步衰减各类型 VP
        for (const key of Object.keys(entry.vpByType) as CheatType[]) {
          entry.vpByType[key] = Math.max(0, entry.vpByType[key] - (DECAY_AMOUNT / 7))
        }
      }
    }
  }

  // ── 持久化 ──

  private startSnapshotTimer(): void {
    this.snapshotTimer = setInterval(() => {
      this.saveSnapshot()
    }, SNAPSHOT_INTERVAL_MS)
  }

  private saveSnapshot(): void {
    try {
      const { writeFileSync, mkdirSync } = require('node:fs')
      const { dirname } = require('node:path')
      const filePath = `${this.dataDir}/vp-snapshot.json`
      const dir = dirname(filePath)
      mkdirSync(dir, { recursive: true })

      const data = {
        version: 1,
        savedAt: Date.now(),
        entries: Array.from(this.entries.entries()),
        penaltyHistory: this.penaltyHistory.slice(-5000),
      }
      writeFileSync(filePath, JSON.stringify(data), 'utf-8')
    } catch (err) {
      console.error('[VPManager] Failed to save snapshot:', err)
    }
  }

  private loadSnapshot(): void {
    try {
      const { existsSync, readFileSync } = require('node:fs')
      const filePath = `${this.dataDir}/vp-snapshot.json`
      if (!existsSync(filePath)) return

      const content = readFileSync(filePath, 'utf-8')
      const data = JSON.parse(content)

      if (data.version === 1 && Array.isArray(data.entries)) {
        for (const [playerId, entry] of data.entries) {
          this.entries.set(playerId, entry)
        }
      }

      if (Array.isArray(data.penaltyHistory)) {
        this.penaltyHistory = data.penaltyHistory
      }

      console.log(`[VPManager] Loaded ${this.entries.size} VP entries, ${this.penaltyHistory.length} penalty records`)
    } catch (err) {
      console.error('[VPManager] Failed to load snapshot:', err)
    }
  }

  // ── 工具方法 ──

  private multiplyDuration(duration: string, multiplier: number): string {
    const DURATION_MS: Record<string, number> = {
      '1h': 3_600_000,
      '6h': 21_600_000,
      '24h': 86_400_000,
      '7d': 604_800_000,
      '30d': 2_592_000_000,
    }

    const ms = DURATION_MS[duration]
    if (ms === undefined) return duration

    const newMs = Math.round(ms * multiplier)

    // 找到最接近的标准时长
    let closest = duration
    let minDiff = Infinity
    for (const [key, val] of Object.entries(DURATION_MS)) {
      const diff = Math.abs(val - newMs)
      if (diff < minDiff) {
        minDiff = diff
        closest = key
      }
    }

    return closest
  }

  private upgradeDuration(duration: string): string {
    const UPGRADE_MAP: Record<string, string> = {
      '1h': '6h',
      '6h': '24h',
      '24h': '7d',
      '7d': '30d',
      '30d': 'permanent',
    }
    return UPGRADE_MAP[duration] ?? duration
  }

  /** 销毁：停止定时器并保存快照 */
  destroy(): void {
    if (this.decayTimer) {
      clearInterval(this.decayTimer)
      this.decayTimer = null
    }
    if (this.snapshotTimer) {
      clearInterval(this.snapshotTimer)
      this.snapshotTimer = null
    }
    this.saveSnapshot()
  }
}
