/**
 * VPManager 单元测试
 * 验证违规积分累加、重置、历史记录等核心逻辑
 */
import { describe, it, expect, beforeEach } from 'vitest'
import { VPManager } from './vp-manager.js'
import type { CheatType, Confidence } from '../contracts/index.js'
import * as fs from 'node:fs'
import * as path from 'node:path'
import * as os from 'node:os'

describe('VPManager', () => {
  let vpManager: VPManager
  let testDir: string

  beforeEach(() => {
    testDir = path.join(os.tmpdir(), `acs-vp-test-${Date.now()}`)
    fs.mkdirSync(testDir, { recursive: true })
    vpManager = new VPManager(testDir, { newPlayerGraceMinutes: 0 })
  })

  it('should start with 0 VP for a new player', () => {
    expect(vpManager.getTotalVP('player1')).toBe(0)
  })

  it('should accumulate VP correctly', () => {
    vpManager.addVP('player1', 'TestPlayer', 'fly', 'high', false, 1.0)
    vpManager.addVP('player1', 'TestPlayer', 'speed', 'low', false, 1.0)

    const total = vpManager.getTotalVP('player1')
    // fly(high=8) * 1.2 = 9.6, speed(low=1) * 1.2 = 1.2, total = 10.8
    expect(total).toBeCloseTo(10.8, 1)
  })

  it('should apply IP shared weight as multiplier', () => {
    vpManager.addVP('player1', 'TestPlayer', 'kill_aura', 'high', false, 2.4)

    const total = vpManager.getTotalVP('player1')
    // kill_aura(high=8) * 1.5 * 2.4 = 28.8
    expect(total).toBeCloseTo(28.8, 1)
  })

  it('should reset VP after penalty confirmation', () => {
    vpManager.addVP('player1', 'TestPlayer', 'fly', 'high', false, 1.0)
    vpManager.addVP('player1', 'TestPlayer', 'speed', 'high', false, 1.0)
    // total = 8*1.2 + 8*1.2 = 9.6 + 9.6 = 19.2

    vpManager.resetVPAfterPenalty('player1', 15) // L1 threshold

    // Reset to 15 * 0.6 = 9
    expect(vpManager.getTotalVP('player1')).toBeCloseTo(9, 1)
  })

  it('should return default stats for unknown player', () => {
    const entry = vpManager.getEntry('unknown_player')
    expect(entry).toBeUndefined()
    expect(vpManager.getTotalVP('unknown_player')).toBe(0)
  })

  it('should track VP by cheat type separately', () => {
    vpManager.addVP('player1', 'TestPlayer', 'fly', 'high', false, 1.0)
    vpManager.addVP('player1', 'TestPlayer', 'kill_aura', 'high', false, 1.0)
    vpManager.addVP('player1', 'TestPlayer', 'speed', 'medium', false, 1.0)

    const entry = vpManager.getEntry('player1')!
    // fly: 8 * 1.2 = 9.6, kill_aura: 8 * 1.5 = 12, speed: 3 * 1.2 = 3.6
    expect(entry.vpByType.fly).toBeCloseTo(9.6, 1)
    expect(entry.vpByType.kill_aura).toBeCloseTo(12, 1)
    expect(entry.vpByType.speed).toBeCloseTo(3.6, 1)
    expect(entry.totalVP).toBeCloseTo(25.2, 1)
  })

  it('should add penalty record to history', () => {
    vpManager.addPenaltyRecord({
      penaltyId: 'penalty-001',
      playerId: 'player1',
      playerName: 'TestPlayer',
      level: 'L1',
      action: 'kick',
      vpAtTime: 15,
      cheatType: 'fly',
      confidence: 'high',
      duration: '',
      reason: '飞行作弊检测',
      autoGenerated: true,
      executedAt: Date.now(),
      result: 'pending',
    })

    const history = vpManager.getPenaltyHistory('player1', 10)
    expect(history.length).toBe(1)
    expect(history[0].cheatType).toBe('fly')
    expect(history[0].level).toBe('L1')
  })

  it('should apply whitelist multiplier (reduced VP for whitelisted players)', () => {
    vpManager.addVP('player1', 'TestPlayer', 'fly', 'high', true, 1.0)
    // fly(high=8) * 1.2 / 2.0 = 4.8
    const total = vpManager.getTotalVP('player1')
    expect(total).toBeCloseTo(4.8, 1)
  })

  it('should apply new player grace period multiplier', () => {
    // 创建一个带宽限期的 VPManager
    const graceDir = path.join(os.tmpdir(), `acs-grace-test-${Date.now()}`)
    fs.mkdirSync(graceDir, { recursive: true })
    const graceManager = new VPManager(graceDir, {
      newPlayerGraceMinutes: 60,
      newPlayerVPMultiplier: 0.5,
    })

    graceManager.addVP('newbie', 'NewPlayer', 'fly', 'high', false, 1.0)
    // fly(high=8) * 1.2 * 0.5(new player) = 4.8
    expect(graceManager.getTotalVP('newbie')).toBeCloseTo(4.8, 1)
  })
})