// @desc GameEvent — discriminated union of all events the Bridge emits to the 3D Frontend
//
// Mirrors AgentShire's 65 GameEvent types, adapted for the anti-cheat monitoring system.

import type { CheatType, Confidence, PlayerPhase } from '../contracts/anticheat-events.js'

export type GameEvent =
  // NPC lifecycle
  | { type: 'npc_spawn'; npcId: string; name: string; role: string; category: string; avatarId?: string; spawn?: { x: number; y: number; z: number } }
  | { type: 'npc_despawn'; npcId: string }
  | { type: 'npc_phase'; npcId: string; phase: PlayerPhase }
  | { type: 'npc_move_to'; npcId: string; target: { x: number; y: number; z: number } }
  | { type: 'npc_glow'; npcId: string; color: string | null }
  | { type: 'npc_emoji'; npcId: string; emoji: string | null }
  | { type: 'npc_anim'; npcId: string; animation: string }
  | { type: 'npc_look_at'; npcId: string; targetNpcId: string }
  | { type: 'npc_emote'; npcId: string; emote: string }

  // Dialog / alerts
  | { type: 'dialog_message'; npcId: string; text: string; isStreaming: boolean }
  | { type: 'alert_popup'; playerId: string; npcId?: string; cheatType: CheatType; confidence: Confidence; message: string }
  | { type: 'player_stats'; npcId: string; stats: Record<string, number> }

  // Scene / mode
  | { type: 'mode_change'; mode: 'monitor' | 'life' }
  | { type: 'scene_switch'; target: 'town' | 'office' }
  | { type: 'progress'; current: number; total: number; label: string }

  // Workstation (monitor station)
  | { type: 'workstation_assign'; npcId: string; stationId: string }
  | { type: 'workstation_screen'; stationId: string; state: Record<string, unknown> }
  | { type: 'workstation_released'; npcId: string; stationId: string }

  // VFX
  | { type: 'fx'; effect: string; params: Record<string, unknown> }

  // Ban animation
  | { type: 'ban_animation'; npcId: string }
  | { type: 'freeze_effect'; npcId: string }
  | { type: 'record_add'; playerId: string; npcId?: string; cheatType: CheatType; timestamp: number }

  // World init
  | { type: 'world_init'; config: Record<string, unknown> }
  | { type: 'set_time'; action: string; hour?: number }
  | { type: 'set_weather'; action: string; weather?: string }

  // Activity
  | { type: 'npc_activity'; npcId: string; icon: string; message: string; time: string }
  | { type: 'npc_activity_status'; npcId: string; success: boolean }
  | { type: 'npc_activity_stream'; npcId: string; delta: string }
  | { type: 'npc_activity_stream_end'; npcId: string }

  // Building enter/leave
  | { type: 'npc_building_enter'; npcId: string; buildingKey: string; stayDurationMs: number }
  | { type: 'npc_building_leave'; npcId: string; buildingKey: string; actualStayMs: number }

  // Escort — town manager escorts NPC to building
  | { type: 'npc_escorting'; npcId: string; buildingKey: string }

  // Phase change — authoritative phase update from PenaltyEngine
  | { type: 'phase_change'; playerId: string; npcId?: string; oldPhase: PlayerPhase; newPhase: PlayerPhase; reason: string; vpTotal: number; cheatType?: CheatType }

  // VP update — violation points change
  | { type: 'vp_update'; playerId: string; totalVP: number; vpByType: Record<string, number> }

  // Penalty event — auto or manual penalty executed
  | { type: 'penalty'; playerId: string; npcId?: string; level: string; action: string; cheatType: CheatType; confidence: Confidence; vp: number; reason: string; autoGenerated: boolean; duration?: string; bannedAt?: number }
