// @desc AntiCheatEvent union type — canonical event contract for the anti-cheat system
//
// 来源: Spigot 插件通过 WebSocket 发射这些事件
// 消费者: Bridge层 (MonitorBridge), Plugin层 (rule-engine, player-tracker)

// ── Shared sub-types ──

export type CheatType = 'fly' | 'speed' | 'kill_aura' | 'x_ray' | 'scaffold' | 'auto_clicker' | 'reach'
export type Confidence = 'low' | 'medium' | 'high'
export type ActionType = 'kick' | 'ban' | 'unban' | 'whitelist_add' | 'whitelist_remove' | 'teleport' | 'freeze' | 'warning'
export type PlayerPhase = 'normal' | 'suspicious' | 'investigating' | 'confirmed' | 'punishing' | 'monitoring' | 'offline'

export interface Evidence {
  metric: string
  value: number
  threshold: number
  duration: number // ms
}

export interface CheatDetection {
  playerId: string
  cheatType: CheatType
  confidence: Confidence
  evidence: Evidence[]
  timestamp: number
}

// ── AntiCheatEvent ──

export type ExitType = 'normal' | 'cheat_ban'

export type AntiCheatEvent =
  // System lifecycle
  | { type: 'system.init'; serverId: string; maxPlayers: number; version: string }

  // Player lifecycle
  | { type: 'player.join'; playerId: string; name: string; ip: string; gameMode: string }
  | { type: 'player.leave'; playerId: string; reason: string; exitType: ExitType }

  // Player data
  | { type: 'player.move'; playerId: string; x: number; y: number; z: number; vx: number; vy: number; vz: number; onGround: boolean }
  | { type: 'player.combat'; attackerId: string; victimId: string; distance: number; angle: number; cps: number; hasLos: boolean }
  | { type: 'player.block'; playerId: string; action: 'break' | 'place'; blockType: string; speed: number }
  | { type: 'player.action'; playerId: string; action: string; state: boolean }
  | { type: 'player.gamemode'; playerId: string; oldMode: string; newMode: string }

  // Detection
  | { type: 'detection'; playerId: string; cheatType: CheatType; confidence: Confidence; evidence: Evidence[] }

  // Action execution
  | { type: 'action_executed'; playerId: string; action: ActionType; actionId?: string; result: string }

  // Ban/Unban execution (from Spigot)
  | { type: 'ban_executed'; playerId: string; name: string; reason: string; duration: string; source: string }
  | { type: 'unban_executed'; playerId: string; name: string; source: string }

  // Alert (aggregated)
  | { type: 'alert'; playerId: string; cheatType: CheatType; confidence: Confidence; message: string }

  // Penalty (auto-generated)
  | { type: 'penalty'; playerId: string; level: string; action: ActionType; cheatType: CheatType; confidence: Confidence; vp: number; reason: string; autoGenerated: boolean }

  // VP update
  | { type: 'vp_update'; playerId: string; totalVP: number; vpByType: Record<CheatType, number> }

  // Error
  | { type: 'error'; message: string; recoverable: boolean }
