// PenaltyLogPanel — auto-penalty log display panel

import type { PenaltyLogEntry, PenaltyLevel, CheatType, Confidence } from '../types.js'
import { PENALTY_LEVEL_LABELS, PENALTY_LEVEL_COLORS, CHEAT_TYPE_LABELS, CHEAT_TYPE_COLORS, CONFIDENCE_LABELS } from '../types.js'

export class PenaltyLogPanel {
  private panel: HTMLElement
  private listEl: HTMLElement
  private closeBtn: HTMLElement
  private entries: PenaltyLogEntry[] = []
  private maxEntries: number = 200

  constructor() {
    this.panel = document.getElementById('penalty-log-panel')!
    this.listEl = document.getElementById('penalty-log-list')!
    this.closeBtn = document.getElementById('penalty-log-close')!

    this.closeBtn.addEventListener('click', () => this.hide())
    this.panel.addEventListener('click', (e) => {
      if (e.target === this.panel) this.hide()
    })

    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && this.isVisible()) this.hide()
    })
  }

  addEntry(entry: PenaltyLogEntry): void {
    this.entries.push(entry)
    if (this.entries.length > this.maxEntries) {
      this.entries = this.entries.slice(-this.maxEntries)
    }

    if (this.isVisible()) {
      this.renderEntry(entry)
    }
  }

  show(): void {
    this.render()
    this.panel.classList.add('visible')
  }

  hide(): void {
    this.panel.classList.remove('visible')
  }

  isVisible(): boolean {
    return this.panel.classList.contains('visible')
  }

  getEntryCount(): number {
    return this.entries.length
  }

  private render(): void {
    this.listEl.innerHTML = ''

    if (this.entries.length === 0) {
      this.listEl.innerHTML = '<div style="padding:20px;text-align:center;color:#5a6478;">暂无处罚记录</div>'
      return
    }

    // 倒序显示（最新在前）
    const sorted = [...this.entries].reverse()
    for (const entry of sorted) {
      this.renderEntry(entry)
    }
  }

  private renderEntry(entry: PenaltyLogEntry): void {
    const el = document.createElement('div')
    el.className = 'penalty-entry'

    // 状态标识映射
    const actionStatusMap: Record<string, { label: string; color: string }> = {
      kick: { label: '已踢出', color: '#e67e22' },
      ban: { label: '已封禁', color: '#e74c3c' },
      kick_ban: { label: '已踢出+封禁', color: '#c0392b' },
      warn: { label: '已警告', color: '#f39c12' },
      freeze: { label: '已冻结', color: '#3498db' },
    }
    const status = actionStatusMap[entry.action] ?? { label: entry.action, color: '#5a6478' }

    el.innerHTML = `
      <div class="penalty-header">
        <span class="penalty-level" style="color:${PENALTY_LEVEL_COLORS[entry.level]};background:${PENALTY_LEVEL_COLORS[entry.level]}20;padding:2px 8px;border-radius:4px;font-weight:600;">
          ${entry.level} ${PENALTY_LEVEL_LABELS[entry.level]}
        </span>
        <span class="penalty-status-badge" style="color:${status.color};background:${status.color}20;padding:2px 8px;border-radius:4px;font-weight:600;font-size:11px;">
          ${status.label}
        </span>
        <span class="penalty-player">${this.escapeHtml(entry.playerName)}</span>
        <span class="penalty-type" style="color:${CHEAT_TYPE_COLORS[entry.cheatType]}">${CHEAT_TYPE_LABELS[entry.cheatType]}</span>
        ${entry.autoGenerated ? '<span class="penalty-auto" style="color:#e67e22;font-size:11px;">自动</span>' : '<span class="penalty-manual" style="color:#3498db;font-size:11px;">手动</span>'}
        <span class="penalty-time" style="color:#5a6478;margin-left:auto;">${this.formatTime(entry.timestamp)}</span>
      </div>
      <div class="penalty-detail">
        <span>VP: ${entry.vp.toFixed(1)}</span>
        <span>置信度: ${CONFIDENCE_LABELS[entry.confidence]}</span>
        <span class="penalty-reason">${this.escapeHtml(entry.reason)}</span>
      </div>
    `
    this.listEl.prepend(el)
  }

  private escapeHtml(str: string): string {
    const div = document.createElement('div')
    div.textContent = str
    return div.innerHTML
  }

  private formatTime(ts: number): string {
    const d = new Date(ts)
    return d.toLocaleTimeString('zh-CN', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' })
  }
}
